### ISSUE TITLE
Can't read any tags

### ISSUE THREAD

**Issue by tinue** [hansemannn/iOS11-NFC-Example#1]
Hi, just wondering: Could you ever read any tag with your phone? I tried both your example and the one from Apple. 
One tag on many that I have shows a "Produkt Erkannt" message, but then it doesn't actually read anything. All other tags time out when reading.
It's apparently very, very beta at this time, but I am wondering if you had more success.

Update: Even when the message "Produkt Erkannt" is shown, the "didDetectNDEFs" method is not being called. A few seconds after the message is shown, I am getting the "readerSessionInvalidationErrorUserCanceled".

**Comment by hansemannn** [comment]
Didn't see it so far, but looks very much like a Beta issue. Can you open a radar at Apple? Should be worth it, so hopefully we can read more NFC tags in Beta 2.

**Comment by tinue** [comment]
I don't really have enough information to say what's wrong. Based on some tests with a Python library, an RC522 reader and a Raspberry Pi it looks like:

- The tags that are not recognized are fresh, or written with the Python library.
- The tags that are showing the "Produkt Erkannt" message yield an "Authentication Error" with the Python library. I believe I have written to these tags in the past with an Android Phone.

So it looks like if the encryption keys are at the default value, the iPhone does not detect the tag at all. If the keys have been changed, the tag is getting read, but it then fails.

The device log shows this, by the way:
Reading NDEF data from tag: <NFTagInternal: 0x1003286b0> { TagTech=A Type=MiFare Identifier=<cb629c21 00000000 0000> }

I don't know if this is enough for a helpful report...

**Comment by tinue** [comment]
I think I see what's happening now. I use a variety of Mitfare 1k tags. Some of them are unused, and contain the original factory keys A&B. CoreNFC can scan them, finds no NDEF tags, and does nothing. I could raise a radar that CoreNFC should instead raise an error "No NDEF tags found", which would make more sense.

The ones that have been written contain changed keys A&B. Apparently CoreNFC can't deal with this, but at least completes the read sequence and drops an error 200. Again, I could raise a radar for a better error message ("Can't read encrypted data" or similar).

Anyway, it has nothing to do with your code, so I'll close the issue. Thanks for taking the time to answer!

**Comment by hansemannn** [comment]
Thank you! If you want, and I would greatly appreciate it, could you write a small paragraph for the readme describing this behavior? I think it would help many developers to debug the issue.
