### ISSUE TITLE
iOS ti.nfc Appcelerator module

### ISSUE THREAD

**Issue by drunnells** [hansemannn/iOS11-NFC-Example#14]
These instructions mention a beta version of ti.nfc for ios, however the link provided does not seem to include the ios module. I apologize if this is the wrong place, but the projects appear to be related. Is the ti.nfc fork here the same beta version mentioned, or is there a better place to find this module?: https://github.com/hansemannn/ti.nfc/tree/2d14f18cf8898963a20eb809b968019cd16edee2/ios

Following similar instructions as iOS11-NFC-Example (using Entitlements.plist with the options mentioned), I've successfully built the module and the example Titanium app, but have run into some trouble and am looking for someplace to find some help. Thanks!

**Comment by hansemannn** [comment]
Hey there! The linked Titanium module was last checked during the beta phase but should still work. It is currently in the final development-stage and will be included in the Titanium SDK 6.3.0 and later. You can track the progress [here](https://jira.appcelerator.org/browse/TIMOB-25313).
