### ISSUE TITLE
nfc

### ISSUE THREAD

**Issue by ChinesePeopleMrLee** [hansemannn/iOS11-NFC-Example#17]
I found my way to your configuration for my project, I can't find in the official version of iOS11 and Xcode 9 on the card to read any information, I would like to ask you about, in a formal environment, your project has a special configuration of others?

**Comment by hansemannn** [comment]
Please see the readme for details, as well as Apple's [documentation](https://developer.apple.com/documentation/corenfc) for advanced details, thanks!
