### ISSUE TITLE
NDEF parser

### ISSUE THREAD

**Issue by jvk75** [hansemannn/iOS11-NFC-Example#19]
Feel free to check out https://github.com/jvk75/NFCNDEFParse
Small library that parses the NDEF messages ("well known types" as defined in NDEF specification) to usable objects. E.g. text type both locale and the payload string are in separate variable.

Early stage but usable. SP type coming soon...

**Comment by hansemannn** [comment]
This is not really related to this example, so I'll close it for clarity. But I love the library! Can you expose it as a real framework (public obj-c header), so Obj-C projects can use it as well? I might have a different project to use it.

**Comment by jvk75** [comment]
Let's see what I can do :) 
Just about to release support for Smart Poster type (with tiny limitations, but should cover majority of tags).

**Comment by jvk75** [comment]
@hansemannn check out the 0.3.0 version or the NFCNDEFParse. It now support usage in Objective-C project (examples coming soon)
https://github.com/jvk75/NFCNDEFParse
