### ISSUE TITLE
iOS 12: NSUserActivity.ndefMessagePayload ?

### ISSUE THREAD

**Issue by scottire** [hansemannn/iOS11-NFC-Example#23]
CoreNFC seems to have not changed much in iOS 12, (I guess [the rumors](https://appleinsider.com/articles/18/05/25/apple-to-reportedly-unlock-iphone-nfc-chip-capabilities-in-june) were wrong).

There is one change in the header files, a `NSUserActivity.ndefMessagePayload`:
`The NFC NDEF message with an Universial Link object that triggers the application launch.`
See [here.](http://codeworkshop.net/objc-diff/sdkdiffs/ios/12.0/CoreNFC.html)
Seems to indicate that you could register for your application to launch when a tag is scanned (from where???) with a specific NDEF message payload. 

Anyone have any more information on this?

**Comment by hansemannn** [comment]
Hey there! I am always looking at the [SDK diff](http://codeworkshop.net/objc-diff/sdkdiffs/ios/12.0/CoreNFC.html) and it seems like there is indeed a new [`ndefMessagePayload`](https://developer.apple.com/documentation/foundation/nsuseractivity/2968463-ndefmessagepayload?language=swift) property for the `NSUserActivity` that you can pass to your view-controller's user activity if used. 

I could update this example to show the actual usage, but don't have too much spare time right now. Does this help a bit already?

**Comment by scottire** [comment]
The documentation says `The NFC NDEF message with an Universial Link object that triggers the application launch.`, which is the part that's confusing because there is no indication of how/where to "trigger the application launch".

**Comment by M0rph3v5** [comment]
maybe it’s built in the os? that you just hold your phone against the tag from wherever and it boots? Or from the lockscreen or homescreen.

**Comment by hansemannn** [comment]
You will probably able to continue or user activity / launch your app via a NFC message, so it may enable background scanning when the app is closed.

**Comment by renssies** [comment]
I saw this API the first day of WWDC and was very curious what is was for, so I went to both the Foundation Lab (NSUserActivity) and the Core NFC lab. All I got from the Core NFC lab was this:

What is the API for?: No Comment!
Was this accidentally made available?: No Comment!
Will it be removed in a future beta?: No Comment!
Is this a new API only available to MFI members? Because as a member I would love to get more information: No Comment!

So yeah, nothing useful.

I also want to add that the property is still available in iOS 12 ~~Beta 3.~~ beta 9

**Comment by YZahringer** [comment]
https://developer.apple.com/documentation/corenfc/adding_support_for_background_tag_reading?changes=latest_minor

**Comment by scottire** [comment]
As @YZahringer linked, we've found out what the `NSUserActivity` `ndefMessagePayload` is for. iPhone Xs, iPhone Xs Max and iPhone Xr have background NFC reading and apps can register to handle payloads found.

The NDEF formatted NFC tag must contain an Apple Universal Link as the first URL found in its NDEF messages. The user is alerted to launch the app, then the app can handle the NDEF message found using the `NSUserActivity` `ndefMessagePayload`. 
If a URI is found that is not an Apple Universal Links for third party apps, iOS supports opening various other URI schemes like SMS, websites and email. 👌

**Comment by hansemannn** [comment]
We should update the example to test this :-). Once I get one of these devices, I'll check it out.

**Comment by xmany** [comment]
Hi Guys, is the example updated accordingly? 
I am trying to implement it, but I got an error saying 
`Value of type 'NSUserActivity' has no member 'ndefMessagePayload'`
Look forward to your implementation!

BTW, happy new year!
