### ISSUE TITLE
Crash appli

### ISSUE THREAD

**Issue by latorrev** [hansemannn/iOS11-NFC-Example#3]
Hi hansemannn,
Thx for your code sample for NFC.
I have tried to use it, but I 've got an error with UITableView.
Please, your help is welcome.
Normally, NFC is working fine with my setup (tried with another basic application, and it works fine).

Here below, log error message...

New NFC Tag detected:
Type name format: NFCTypeNameFormat
Payload: 4036 bytes
Type: 12 bytes
Identifier: 0 bytes
=================================================================
Main Thread Checker: UI API called on a background thread: -[UITableView reloadData]
PID: 439, TID: 69069, Thread name: (none), Queue name: com.apple.corenfc.readersession, QoS: 0
Backtrace:
4   NFC-Example                         0x000000010277d43c _T011NFC_Example22NFCTableViewControllerC13readerSessionySo013NFCNDEFReaderG0C_SaySo14NFCNDEFMessageCG14didDetectNDEFstF + 2600
5   NFC-Example                         0x000000010277d91c _T011NFC_Example22NFCTableViewControllerC13readerSessionySo013NFCNDEFReaderG0C_SaySo14NFCNDEFMessageCG14didDetectNDEFstFTo + 124
6   libdispatch.dylib                   0x00000001032b1654 _dispatch_call_block_and_release + 24
7   libdispatch.dylib                   0x00000001032b1614 _dispatch_client_callout + 16
8   libdispatch.dylib                   0x00000001032c1008 _dispatch_queue_serial_drain + 716
9   libdispatch.dylib                   0x00000001032b4e58 _dispatch_queue_invoke + 340
10  libdispatch.dylib                   0x00000001032c21c4 _dispatch_root_queue_drain_deferred_wlh + 412
11  libdispatch.dylib                   0x00000001032c97fc _dispatch_workloop_worker_thread + 868
12  libsystem_pthread.dylib             0x00000001a87e71e8 _pthread_wqthread + 924
13  libsystem_pthread.dylib             0x00000001a87e6e40 start_wqthread + 4
2017-06-12 11:12:32.207609+0200 NFC-Example[439:69069] [reports] Main Thread Checker: UI API called on a background thread: -[UITableView reloadData]
PID: 439, TID: 69069, Thread name: (none), Queue name: com.apple.corenfc.readersession, QoS: 0
Backtrace:
4   NFC-Example                         0x000000010277d43c _T011NFC_Example22NFCTableViewControllerC13readerSessionySo013NFCNDEFReaderG0C_SaySo14NFCNDEFMessageCG14didDetectNDEFstF + 2600
5   NFC-Example                         0x000000010277d91c _T011NFC_Example22NFCTableViewControllerC13readerSessionySo013NFCNDEFReaderG0C_SaySo14NFCNDEFMessageCG14didDetectNDEFstFTo + 124
6   libdispatch.dylib                   0x00000001032b1654 _dispatch_call_block_and_release + 24
7   libdispatch.dylib                   0x00000001032b1614 _dispatch_client_callout + 16
8   libdispatch.dylib                   0x00000001032c1008 _dispatch_queue_serial_drain + 716
9   libdispatch.dylib                   0x00000001032b4e58 _dispatch_queue_invoke + 340
10  libdispatch.dylib                   0x00000001032c21c4 _dispatch_root_queue_drain_deferred_wlh + 412
11  libdispatch.dylib                   0x00000001032c97fc _dispatch_workloop_worker_thread + 868
12  libsystem_pthread.dylib             0x00000001a87e71e8 _pthread_wqthread + 924
13  libsystem_pthread.dylib             0x00000001a87e6e40 start_wqthread + 4
2017-06-12 11:12:44.163074+0200 NFC-Example[439:69069] *** Assertion failure in -[UITableView _dequeueReusableCellWithIdentifier:forIndexPath:usingPresentationValues:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3678.13/UITableView.m:7518
2017-06-12 11:12:44.170954+0200 NFC-Example[439:69069] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'unable to dequeue a cell with identifier NFCTableCell - must register a nib or a class for the identifier or connect a prototype cell in a storyboard'
*** First throw call stack:
(0x184ee04e8 0x1a7850528 0x184ee03bc 0x186b5dc24 0x18c01c7cc 0x18be654e8 0x10277c238 0x10277c660 0x18c02c844 0x18c02cd5c 0x18c00e9c4 0x18bdd26a0 0x18bcfe4f0 0x18b21aa84 0x18b20ed70 0x18b20ec2c 0x18b18588c 0x18b1acae4 0x18b1ace7c 0x1a87e7898 0x1a87e75e8 0x1a87e7380 0x1a87e6e40)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by hansemannn** [comment]
Whoops, having a local fix available, will push asap!

**Comment by hansemannn** [comment]
Just pushed a fix! Unfortunately I do not have an NFC tag with me right now, so please try it out :-).

**Comment by latorrev** [comment]
Cool ...it works better right now. I m able to detect NDEF , then to display "1 record" in Table View.
Otherwise, I have an error when I select record message into table view : I think it is normal as it is not implemented yet.

New NFC Tag detected:
Type name format: NFCTypeNameFormat
Payload: 4036 bytes
Type: 12 bytes
Identifier: 0 bytes
Error reading NFC: Session is invalidated by user cancellation
2017-06-12 15:28:07.553518+0200 NFC-Example[535:113914] [] <<<< FigVirtualFramebufferServer >>>> FigVirtualFramebufferGetMaxCount: unsupported operation
2017-06-12 15:28:07.553656+0200 NFC-Example[535:113914] [] <<<< FigVirtualFramebufferServer >>>> FigVirtualFramebufferGetFramebufs: unsupported operation
2017-06-12 15:28:07.553751+0200 NFC-Example[535:113914] [] <<<< FigVirtualFramebufferInstallation >>>> FigInstallVirtualDisplay_block_invoke: FigVirtualFramebufferGetFramebufs failed (0 framebufs)

**Comment by hansemannn** [comment]
Yep, let's wait what Beta 2 brings :-). Thx!

**Comment by latorrev** [comment]
Thx a lot for your contribution !!! It helps !!!
