### ISSUE TITLE
Can not read tags

### ISSUE THREAD

**Issue by NickAtGit** [hansemannn/iOS11-NFC-Example#4]
I got the app running but my iPhone 7 Plus does not recognise tags. Tried all my tags on a Pixel Phone and they are all working. Even rebooting like @tinue suggested does not work for me. Your code looks fine to me. Hopefully it gets better in Beta 2.

**Comment by hansemannn** [comment]
Agree. It's pretty hard to find a working NDEF-NFC-Tag so far, let's see what Beta 2 brings!
