### ISSUE TITLE
re: read error with encrypted sectors

### ISSUE THREAD

**Issue by mvayngrib** [hansemannn/iOS11-NFC-Example#5]
could it be that you need the decryption keys in order to even read the tag? For example, on US passports, the keys are derived from the passport data - name, birth date, etc.

I see in this Android NFC blog (see step 3) that they weren't able to read the data without possession of the keys: https://randomoracle.wordpress.com/2012/08/27/reading-the-us-passport-using-an-android-phone-overview/

**Comment by hansemannn** [comment]
That is very possible. I did not try with a US-passport so far (I am from 🇩🇪), but especially something like a passport will have additional security enhancements to prevent external people to read it. As for iOS 11 and `CoreNFC`, I think Apple is still at an early stage implementing all NFC-requirements.

I have updated the readme with some general NDEF-information, maybe that will help you to get started with your own (non passport) tags 😇.
