### ISSUE TITLE
Is the RFID API is a private API?

### ISSUE THREAD

**Issue by andymedvedev** [hansemannn/iOS11-NFC-Example#6]
Thanks for great example. But I have a question. ISO15693 API is private Apple API or it's just not presented yet?

**Comment by hansemannn** [comment]
I guess it's just not implemented in the most recent iOS 11 Beta 2 so far. I've added it to be completed when it get's supported. There are docs for it and it's available from the public API, so I guess they need to add the functionality. Might be worth to file a bug-report for it.
