### ISSUE TITLE
Does NFC capability requires a paid Apple developer membership ?

### ISSUE THREAD

**Issue by lbalogh** [hansemannn/iOS11-NFC-Example#7]
Hi,

I only have a free developer account and can't get this project to compile. I always get errors about missing capabilities and entitlements.

The matrix here does not includes NFC (yet) :

https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/SupportedCapabilities/SupportedCapabilities.html#//apple_ref/doc/uid/TP40012582-CH38-SW1

As far as I know provisioning profiles can't be be managed from the developer portal with a free account, is that correct ? From what I understand it's managed automatically by Xcode.

Thanks

Ludovic

**Comment by hansemannn** [comment]
I think Xcode 7 and later allows developer to run apps on the device without the paid membership, but since you need to configure the entitlements online, I could think of needing an actual paid account, yes. Please consult Apple for this kind of questions, they will have a better answer.
