### ISSUE TITLE
RFID has a different error message

### ISSUE THREAD

**Issue by alpascual** [hansemannn/iOS11-NFC-Example#8]
Looks like RFID now is missing an unknown entitlement key in beta 3
`Error reading RFID-Tag: Required entitlement is missing`

**Comment by hansemannn** [comment]
I looked through the Beta 2 -> Beta 3 API changes and could not find relevant changes for the RFID-API. Apple also still does not link it in their [web-docs](https://developer.apple.com/documentation/corenfc?language=objc), so I do not think they want you to use it so far. If you find a proper entitlement that actually gets accepted, let me know! 

I will leave this issue open for now, thx!

**Comment by alpascual** [comment]
Doesn't look like Apple is sharing that information in beta 3 so far. We may have to wait until beta 4. Thanks

**Comment by haemi** [comment]
does this mean that it worked in beta 2 but not in beta 3?

**Comment by hansemannn** [comment]
Nope, neither in Beta 2 or 3

**Comment by haemi** [comment]
last question regrading this and RFID: does RFID in this case mean that longer distances (some ~ 10cm  or so) are possible to scan or still only 0-2 cm?

**Comment by hansemannn** [comment]
Active RFID tags can even be used from 100m, crazy right? So yes, the RFID distance can be way longer, see [this article](http://blog.atlasrfidstore.com/rfid-vs-nfc) for more infos.

**Comment by haemi** [comment]
but passive ones? With the iPhone?

**Comment by hansemannn** [comment]
The linked article will help ;-)
> Passive RFID tags do not have their own power source. Instead, they are powered by the electromagnetic energy transmitted from the RFID reader. Because the radio waves must be strong enough to power the tags, passive RFID tags have a read range from near contact and up to 25 meters.

**Comment by haemi** [comment]
unfortunately it doesn't help; I don't know if the iPhone is strong enough to "ping" the passive token, because e.g. I tested an Android Phone which recognized the RFID tag but I had to bring it very, very close to the tag (~ 2cm)

**Comment by Dalein** [comment]
What about RFID in Beta 4?

**Comment by hansemannn** [comment]
Nope 😐. Just tried using Beta 4 - while the search dialog pops up for around a second, it then closes automatically and aborts with the error `Error reading RFID-Tag: Required entitlement is missing` inside the console. Does anyone know about RFID entitlements?

**Comment by M0rph3v5** [comment]
no new options in the dropdown or anything?

**Comment by hansemannn** [comment]
👎 No new option, no new docs and not even an API-change (diff'd it) regarding CoreNFC from Beta 3 to 4.

**Comment by ocastx** [comment]
Beta 5 was just released, could not check it yet

**Comment by hansemannn** [comment]
No new `CoreNFC` changes between Beta 4 and 5 (see [diff](http://codeworkshop.net/objc-diff/sdkdiffs/ios/11.0b5/)) ...

**Comment by jonathanjacob** [comment]
Beta 6 was released yesterday. In the release notes I see under resolved:
• Reader mode utilizing NFC now works correctly on supported devices. (32721033) 

was this the related radar?

**Comment by dickwu** [comment]
beta 6 still not work

**Comment by hansemannn** [comment]
Still not possible to read RFID-chips. I believe it will not be supported in iOS 11 GA, since it's all about NFC explicitly. I'll keep this issue open to track progress.

**Comment by transparentmask** [comment]
I did some work in current beta. I found some strings in /usr/libexec/nfcd and /usr/libexec/seld which are extracted from ipsw package. So, the RFID string in entitlement should be "ISO15693".

![screen shot 2017-08-24 at 21 08 44](https://user-images.githubusercontent.com/121370/29667899-c54d7e50-8910-11e7-8aa6-e936a725a1b1.png)

![1](https://user-images.githubusercontent.com/121370/29668112-98229bc6-8911-11e7-8095-9fd6243fff0d.png)

But there is a private class named "NFServiceWhitelistChecker". And it have some methods like "-[NFServiceWhitelistChecker _initCoreNFCEntitlements:]", "-[NFServiceWhitelistChecker nfcISO15693ReaderAccess]", "-[NFServiceWhitelistChecker nfcNDEFAccess]".

I also noticed, if I set "ISO15693" in entitlement, the device log will show me "Skipping a profile because of error 0xe8008012" and "entitlement '\<private\>' has value not permitted by provisioning profile '\<private\>'". But if I set the meaningless string "test123" in entitlement, it can pass the validation.

![screen shot 2017-08-24 at 21 09 47](https://user-images.githubusercontent.com/121370/29667908-ce2d4712-8910-11e7-94a2-3ef4b25ad390.png)

So, maybe the NFServiceWhitelistChecker class done an extra check so that "ISO15693", even "com.apple.developer.nfc.readersession.iso15693.tag-identifiers" can not pass the validation.

**Comment by andy-fueled** [comment]
I am trying to get the UID of a tag, and tried to create a `NFCISO15693ReaderSession`, but am also getting `Error reading RFID-Tag: Required entitlement is missing`. Do you have any additional info on how to get around this?

**Comment by hansemannn** [comment]
Coming back to this, it should obviously either be exposed by Apple properly or not be an option for developers. It cannot be that they have a public RFID API that nobody can use in a Beta 10 close to GM. Did anyone get the chance to talk to Apple about this?

**Comment by transparentmask** [comment]
I try with iOS 11 GM Seed & Xcode 9 GM Seed. When I setting entitlement with "ISO15693", the app can not install in my iPhone 7. And If not fill with "ISO15693", will show me  "Error reading RFID-Tag: Required entitlement is missing".

So, read RFID is not allow. Just waiting someone to try with iPhone 8.

**Comment by jasjukaitis** [comment]
Not sure if they were too lazy to remove all the NFCISO15693 from the SDK or to extend the documentation. I also tried different entitlements, but none are working. Really frustrating. :(

**Comment by hansemannn** [comment]
@transparentmask Did you get an iPhone 8 to test already? Would wonder if it works there!

**Comment by rtnlsltn** [comment]
Couldn't get anything to read with an iPad Pro so I picked up an iPhone 7. The "ready to scan" dialogue opens up but it won't recognize any of my tags....

**Comment by egcode** [comment]
Tried with iPhone 8, same error: ```Error reading RFID-Tag: Required entitlement is missing```

**Comment by a81j** [comment]
How about iOS 11.1 now that it has released.

**Comment by hansemannn** [comment]
No `CoreNFC` api's added.

**Comment by mozeryansky** [comment]
@transparentmask Were you able to get past the entitlement issue? I added the entitlement you found but Xcode won't run the app on my phone, I get an error "The executable was signed with invalid entitlements.":
The entitlements specified in your application’s Code Signing Entitlements file are invalid, not permitted, or do not match those specified in your provisioning profile. (0xE8008016).

**Comment by transparentmask** [comment]
I can not run test app with NFCISO15693 entitlements (both "ISO15693" and "com.apple.developer.nfc.readersession.iso15693.tag-identifiers").

**Comment by Joohansson** [comment]
iOS 11.2 on iPhone 7: Error reading RFID-Tag: Required entitlement is missing
Still no successful attempts?

**Comment by mozeryansky** [comment]
I filed a bug on Apple about allowing NFC and they closed it as "Not to be fixed", so as far as I can tell they don't plan to support it.

**Comment by hansemannn** [comment]
@mozeryansky Based on that feedback, I'll close this issue for now, but will be happy to reopen it as there is progress on it in future versions of iOS. Thanks everyone for this great discussion!

**Comment by kaqijiang** [comment]
hopes to use this feature, sustained attention.  iphone7 11.3 Error reading RFID-Tag: Required entitlement is missing

**Comment by kaqijiang** [comment]
Does iOS12 support RFID? Has anyone been trying?

**Comment by hansemannn** [comment]
Nope, [these](codeworkshop.net/objc-diff/sdkdiffs/ios/12.0/CoreNFC.html) are the only iOS 12 CoreNFC changes so far. More maybe to come over the next 3 months.

**Comment by jpsubbarayalu** [comment]
Hi @hansemannn,
Tried using iPhone 7 with iOS 11.4, Still i am getting the same error,
Error reading RFID-Tag: Required entitlement is missing

**Comment by kukudy** [comment]
Unfortunately - I tried with 12.1.4 - same results :(
Must have access to RFID!

**Comment by cbrockschmidt** [comment]
Some more tag types seem to be supported in iOS13, including ISO7816, ISO15693, FeliCa, and MIFARE: 
https://developer.apple.com/documentation/corenfc?changes=latest_minor  
https://developer.apple.com/documentation/corenfc/nfctagreadersession?changes=latest_minor
Has anyone already had the chance to try this?

**Comment by hansemannn** [comment]
@cbrockschmidt Will extend the repo this week and let you know

**Comment by BadChoice** [comment]
in ios13 you get this error

`Use of undeclared type 'NFCISO15693ReaderSession'`

Can't find if there is a new way to work with it?

**Comment by BadChoice** [comment]
Ok, found that now we have to use

`NFCTagReaderSession(pollingOption: [.iso14443, .iso15693/*, .iso18092*/], delegate: self, queue: nil)`

And add the `TAG` value into the entitlements too, (I commented the 18092 since seems it is not a TAG hehe)

however it doesn't seem to find my RFID tag :(

**Comment by YangYouYong** [comment]
@cbrockschmidt  have you tried ISO15693 tag  in iOS 13 ?
Use the API ```NFCTagReaderSession(pollingOption: [.iso14443, .iso15693], delegate: self, queue: nil) ``` can detect the ISO15693 tag . but does not support ```sendCustomCommandWithConfiguration:completionHandler:  ``` method
